FROM python:3.6

RUN useradd -d /home/opacity -m opacity
WORKDIR /home/opacity

# If pulling directly from repo, use:
#ADD https://github.com/<user>/<repo>/tarball/master .
#RUN tar xpvf master --strip-components=1

RUN python3 -m venv venv
RUN venv/bin/pip3 install --upgrade pip
RUN venv/bin/pip3 install wheel
COPY requirements_webapp.txt requirements_webapp.txt
RUN venv/bin/pip3 install -r requirements_webapp.txt

# use for local development
COPY app app
COPY common/functions.py app/functions.py
COPY opacity_webapp.py opacity_webapp.py
COPY start_webapp_http.sh start_webapp_http.sh
COPY start_webapp_https.sh start_webapp_https.sh
COPY celeryconfig.py app/celeryconfig.py

USER opacity