class Constants:
    FILENAME_MAX_LENGTH = 256
    CURRENT_VERSION = 1
    IV_BYTE_LENGTH = 16
    TAG_BYTE_LENGTH = 16
    TAG_BIT_LENGTH = TAG_BYTE_LENGTH * 8
    DEFAULT_BLOCK_SIZE = 64 * 1024
    BLOCK_OVERHEAD = TAG_BYTE_LENGTH + IV_BYTE_LENGTH
    DEFAULT_PART_SIZE = 128 * (DEFAULT_BLOCK_SIZE + BLOCK_OVERHEAD)